name: lookin_empat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  firebase_database: ^10.5.5
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  flutter_bloc: ^8.1.5
  flutter_hsvcolor_picker: ^1.5.0
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/icons/section/
