// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo6BXPdRX7_43Db9wBRPdR2KziE3bWowc',
    appId: '1:1038515314255:web:fb7ce5d1717b8b69e2143a',
    messagingSenderId: '1038515314255',
    projectId: 'lookin-b9b19',
    authDomain: 'lookin-b9b19.firebaseapp.com',
    storageBucket: 'lookin-b9b19.appspot.com',
    measurementId: 'G-F2VPX0KW43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARWaUVTlANgfRViBtDHJkRdogxmtJfmnY',
    appId: '1:1038515314255:android:15bb71e2f7b5ad71e2143a',
    messagingSenderId: '1038515314255',
    projectId: 'lookin-b9b19',
    storageBucket: 'lookin-b9b19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPHHqR0rb8CRqWYIra4rNuyTldDubLkNE',
    appId: '1:1038515314255:ios:9607d91b1bc52a98e2143a',
    messagingSenderId: '1038515314255',
    projectId: 'lookin-b9b19',
    storageBucket: 'lookin-b9b19.appspot.com',
    iosBundleId: 'com.example.lookinEmpat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPHHqR0rb8CRqWYIra4rNuyTldDubLkNE',
    appId: '1:1038515314255:ios:9607d91b1bc52a98e2143a',
    messagingSenderId: '1038515314255',
    projectId: 'lookin-b9b19',
    storageBucket: 'lookin-b9b19.appspot.com',
    iosBundleId: 'com.example.lookinEmpat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo6BXPdRX7_43Db9wBRPdR2KziE3bWowc',
    appId: '1:1038515314255:web:2de75110851c22e0e2143a',
    messagingSenderId: '1038515314255',
    projectId: 'lookin-b9b19',
    authDomain: 'lookin-b9b19.firebaseapp.com',
    storageBucket: 'lookin-b9b19.appspot.com',
    measurementId: 'G-DSCLHFZC99',
  );
}
